
import '@/styles/globals.css'
import { Box, Grid, Hidden, IconButton, PaletteMode } from '@mui/material';
import CssBaseline from '@mui/material/CssBaseline';
import { ThemeProvider, createTheme, useTheme } from '@mui/material/styles';
import type { AppProps } from 'next/app'
import { Inter } from 'next/font/google' // we can change font here
import Head from 'next/head'
import React from 'react'

import WbSunnyIcon from '@mui/icons-material/WbSunny';
import NightlightRoundIcon from '@mui/icons-material/NightlightRound';
import Image from 'next/legacy/image'

import headerImg from './image/header.png'
import headerImgDark from './image/dark.jpg'
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import { amber, blue, deepOrange, grey } from '@mui/material/colors';


const inter = Inter({ subsets: ['latin'] }) // we put font her for include whole project


export default function App({ Component, pageProps }: AppProps) {
  const [mode, setMode] = React.useState<PaletteMode>('light')


  const theme = createTheme({
    typography: {
      fontFamily:
        'Almarai',
    },
    palette: {
      mode,
      ...(mode === 'light'
        ? {
          // palette values for light mode
          primary: amber,
          divider: amber[200],
          text: {
            primary: '#C7C7C7',
            secondary: grey[800],
          },
          secondary: {
            // This is green.A700 as hex.
            main: '#FFFFFF',
          }
        }
        : {
          // palette values for dark mode
          primary: deepOrange,
          divider: deepOrange[700],
          background: {
            default: '#031C30',
            
          },
            secondary: {
              // This is green.A700 as hex.
              main: '#052943',
          },
          text: {
            primary: '#fff',
            secondary: grey[500],
          },
        }),

    }
  });

  const toggleTheme = () => {
    setMode(mode === 'light' ? 'dark' : 'light')
  }

  return (
    <div className={inter.className}>
      <Head>
        <title>TO DO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Almarai:wght@800&display=swap" rel="stylesheet" />  {/* add link for a font take from google font to add new font */}
      
      </Head>

      <Box style={{ position: 'relative', top: 0 ,margin:0 , overflow: 'hidden'}}>
        {mode === 'dark' ? <Image
          src={headerImgDark}
          alt="Header Img"
          height={340}
          width={1280}
          layout="responsive" /> : <Image
          src={headerImg}
          alt="Header Img"
          objectFit="cover"
          height={340}
          width={1280}
          layout="responsive" />}
      </Box>

      {/* ////////////////// Dark Mode ////////////////// */}



      <Container maxWidth="sm" sx={{
            position: 'relative',left: 5, bottom: {lg: 270 , md: 260 , sm: 240, xs: 150}, }}>
        <Grid container spacing={0.5} minHeight={160} >
          <Grid item sm display="flex" justifyContent="left" alignItems="center">
            <Typography sx={{ display: 'inline', fontSize: 36, textAlign: 'left', letterSpacing: 8, fontFamily: 'Almarai', color: 'white' }}> TODO </Typography>
          </Grid>

          <Grid  display="flex" justifyContent="center" alignItems="center">
            <IconButton onClick={toggleTheme} size="large">
              {theme.palette.mode === 'dark' ? <WbSunnyIcon fontSize="large" sx={{ color: 'white' }} /> : <NightlightRoundIcon fontSize="large" sx={{ color: 'white' }} />}
            </IconButton>
          </Grid>
        </Grid>
      </Container>

      <ThemeProvider theme={theme} >
        <CssBaseline />
        <Component {...pageProps}/>
      </ThemeProvider>
    </div>
  )
}
